export const mockEpisodes = [
  {
    id: 1,
    title: "The Future of AI: Opportunities and Challenges",
    description: "Explore the latest developments in artificial intelligence and their impact on society.",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop",
    duration: "18:32",
    category: "Tech Analysis",
    date: "2024-03-15",
    views: 15420,
  },
  {
    id: 2,
    title: "Understanding Climate Change: Latest Research",
    description: "A deep dive into recent climate science discoveries and their implications.",
    thumbnail: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop",
    duration: "24:15",
    category: "Science Deep Dives",
    date: "2024-03-12",
    views: 12350,
  },
  {
    id: 3,
    title: "Digital Privacy in the Modern Age",
    description: "Examining the state of privacy in our increasingly connected world.",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop",
    duration: "21:45",
    category: "Tech Analysis",
    date: "2024-03-10",
    views: 18670,
  },
  {
    id: 4,
    title: "The Evolution of Social Media",
    description: "Analyzing how social platforms have transformed communication and society.",
    thumbnail: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
    duration: "19:28",
    category: "Cultural Trends",
    date: "2024-03-08",
    views: 21430,
  },
  {
    id: 5,
    title: "Global Democracy: Challenges and Solutions",
    description: "Examining the state of democracy worldwide and potential paths forward.",
    thumbnail: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&auto=format&fit=crop",
    duration: "26:10",
    category: "Political Insights",
    date: "2024-03-05",
    views: 16890,
  },
  {
    id: 6,
    title: "Quantum Computing Explained",
    description: "Breaking down the complexities of quantum computing for everyone.",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop",
    duration: "22:45",
    category: "Science Deep Dives",
    date: "2024-03-02",
    views: 19750,
  },
]

export const mockBlogPosts = [
  {
    id: 1,
    title: "The Ethics of Artificial Intelligence in Decision Making",
    slug: "ethics-ai-decision-making",
    excerpt: "As AI systems become more prevalent in critical decision-making processes, we must carefully consider the ethical implications and establish proper guidelines.",
    content: "Full article content here...",
    coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop",
    category: "Tech Analysis",
    date: "2024-03-15",
    author: {
      name: "Sarah Chen",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop",
    },
    tags: ["AI", "Ethics", "Technology", "Future"],
  },
  {
    id: 2,
    title: "Understanding Quantum Supremacy",
    slug: "quantum-supremacy-explained",
    excerpt: "A deep dive into what quantum supremacy means and its implications for the future of computing and cryptography.",
    content: "Full article content here...",
    coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop",
    category: "Science Deep Dives",
    date: "2024-03-12",
    author: {
      name: "Michael Ross",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop",
    },
    tags: ["Quantum Computing", "Physics", "Technology"],
  },
  {
    id: 3,
    title: "The Rise of Digital Democracy",
    slug: "digital-democracy-rise",
    excerpt: "How technology is transforming democratic participation and governance in the modern age.",
    content: "Full article content here...",
    coverImage: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&auto=format&fit=crop",
    category: "Political Insights",
    date: "2024-03-10",
    author: {
      name: "Elena Martinez",
      avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&auto=format&fit=crop",
    },
    tags: ["Politics", "Democracy", "Technology"],
  },
]

export const mockPopularTags = [
  { name: "Technology", count: 24 },
  { name: "Science", count: 18 },
  { name: "AI", count: 15 },
  { name: "Politics", count: 12 },
  { name: "Culture", count: 10 },
  { name: "Climate", count: 8 },
  { name: "Innovation", count: 7 },
  { name: "Ethics", count: 6 },
]